### ISSUE TITLE
Whole Forum Grading - Mlang 2 - Unexpected token m in JSON at position 1

### ISSUE THREAD

**Issue by mifantrax** [iarenaza/moodle-filter_multilang2#20]
How to reproduce

1. 1. Create a forum
2. 2. Set grading to Whole Forum Grading
3. Set forum Name using multi-lang tags
4. Save
5. Open forum and co to Grade Users
This prevents  from using the whole forum grading feature. The problem is also partly present using native supported moodle multi-language tags however there it is only an ui issue and using Multilang 2 prevents from grading.
Thank you so much for looking into this.
![json_mlang_wholeforumgrading](https://user-images.githubusercontent.com/2910506/100519147-61c3a800-3196-11eb-8e56-3cd98d093674.png)

**Comment by izendegi** [comment]
Hi @mifantrax 

I've been able to reproduce that issue, but it seems like the bug is on the Moodle core side that doesn't manage filters correctly in the whole forum grading functionality added on Moodle 3.8 instead of a bug of the filter itself.

We're trying to find a workaround for this issue, but meanwhile you may want to open the issue on tracker.moodle.org.

**Comment by mifantrax** [comment]
Thank you Iñigo, I have opened an issue on the tracker some time ago but no visible action was taken.
https://tracker.moodle.org/browse/MDL-69097
Using the regular Moodle multilang tags allows you to go through and grade without filtering the tags and simply displaying them on the page.
However using multilang2 does not go through at all spiting the SyntaxError.
Thank you!

**Comment by izendegi** [comment]
Oh, great, I've answered and updated the issue's title there, I'll close this issue and let's follow the conversation there, ok?

**Comment by mifantrax** [comment]
Sure, thank you for the correction. Hopefully you attract more attention.
Have a great time of the day!
Mihail Bojonca
*TCM International Institute*
Haus Edelweiss, Austria
Director of Information Technologies
Schedule a video call with me
<https://calendly.com/mihai-bojonca/google-meet-with-mihai>
or
You may find me on:
email: mihai.bojonca@tcmi.edu, admin@tcmi.edu
Mobile: +43 676 3158142
Office: +43 225 8727 (ext)156
Viber: +43 676 3158142
WhatsApp: +43 676 3158142 (mihai.bojonca)
