### ISSUE TITLE
Multilang filter not applied in Calendar Block

### ISSUE THREAD

**Issue by mifantrax** [iarenaza/moodle-filter_multilang2#21]
Started another issue that is related only to Multilang2
Thank you for looking into that.
https://tracker.moodle.org/browse/MDL-70355

**Comment by izendegi** [comment]
Hi @mifantrax 

This one is another core issue, I'll close this one and let's follow working on it at [MDL-70355](https://tracker.moodle.org/browse/MDL-70355).
