### ISSUE TITLE
Multilang 2 is not working with Moodle blog items titles !!!

### ISSUE THREAD

**Issue by naamaan** [iarenaza/moodle-filter_multilang2#22]
Hi,
I'm trying the filter with Moodle v10 default blog, but the title isn't translated while the blog body is responding correctly.
Any help please?
Regards,
![BlogTranslation](https://user-images.githubusercontent.com/2176593/105639079-df4a2280-5e7e-11eb-9ab8-846ec6189d67.png)

**Comment by lucaboesch** [comment]
@naamaan that doesn't look like an standard Moodle block and the cause for that title not being filtered is likely in your custom theme. It will not filter even if you use the classical multilang syntax https://docs.moodle.org/310/en/Multi-lingual_Content_filter (please cross check) so this issue isn't to be solved by this plugin here.

**Comment by lucaboesch** [comment]
I found this one https://tracker.moodle.org/browse/MDL-70705 though.
