### ISSUE TITLE
Language filtering not working for Some Course Content

### ISSUE THREAD

**Issue by sabetech** [iarenaza/moodle-filter_multilang2#24]
![image](https://user-images.githubusercontent.com/4713955/124190000-1917f880-dab1-11eb-8243-6dde8539fb14.png)
![image](https://user-images.githubusercontent.com/4713955/124190056-2d5bf580-dab1-11eb-8c7b-ec6a887f6cc0.png)
![image](https://user-images.githubusercontent.com/4713955/124190510-eb7f7f00-dab1-11eb-8620-dffb12578e8e.png)

The images uploaded are examples of my usage of the language filter and it does not seem to work. I'm not sure if there's a way to address this in any way.

**Comment by iarenaza** [comment]
Just to make sure this is actually a bug, do you have the `filter_multilang2` enabled, and configured to be applied to `Content and headings`? (as opposed to just `Content`)

Also, are you using a standard Moodle theme?

**Comment by sabetech** [comment]
Hi, I configured the plugin to apply to content and headings and it's working now. Thank you
