### ISSUE TITLE
If Canadian French is selected, an additional translation in French is provided in mlang plugin

### ISSUE THREAD

**Issue by Laurynas-M** [iarenaza/moodle-filter_multilang2#25]
Hello,

Thank you for amazing plugin.

However, there is a problem, then this plugin is used with two language packs: Canadian French with language code ** fr_ca ** and French with language code ** fr **.

Here are steps to replicate issue:

1. Install/have additional two language packs: Canadian French with language code **fr_ca** and French with language code **fr**.
2. Use mlang plugin in any available places (course, activities, block, menu etc.) with these two languages, example: **{mlang fr_ca}your_content_in_Canadian French{mlang}{mlang fr}your_content_in French{mlang}**
3. ISSUE: Choose Canadian French language with code **fr_ca**, then the text will be displayed with two languages fr_ca and fr translations, result: **your_content_in_Canadian Frenchyour_content_in French**
4. Choose French language with code **fr**, then text will be displayed correctly - only with fr translation, result: **your_content_in French**

Could you solve this issue, that once Canadian French *fr_ca** language is chosen, {mlang} would shown only translation in **fr_ca** ?
How long will it take to resolve this?

Thank you in advance.
Let me know, if you have any questions.

**Comment by KepaUrzelai** [comment]
Hello @Laurynas-M,

I was able to replicate your problem and it looks like the filter adds both contents, one matching the chosen child language (fr_ca) and the other one matching the parent language (fr), whenever this last is also defined.

The point of adding the parent language makes sense when no tagged content is defined for the child (the one being used by the site), in the other cases a very similar text would be duplicated in the content.

I think that with this little patch the previously mentioned functionality keeps working and the problem you described is solved, as the filter shouldn't return more than one filtered content.

**Comment by KepaUrzelai** [comment]
Sorry, I noticed that the previous patch is only valid when the child language is the first one been filtered, as in your example:
**{mlang fr_ca}your_content_in_Canadian French{mlang}{mlang fr}your_content_in French{mlang}**

As soon as I have time, I will work on a more appropriate solution.

**Comment by iarenaza** [comment]
I just want to comment that the currently implemented behaviour is exactly the same behaviour implemented by the standard Moodle Multilang filter.

**Comment by KepaUrzelai** [comment]
Good morning @iarenaza,

I'm sorry to say that the standard plugin doesn't show both of the contents when those are defined and the child language is the one being used.

In this example the current language is set to Canadian French, and both labels have content defined for both, French and Canadian French languages:

<img src="https://user-images.githubusercontent.com/43538080/127110950-ffdb39ce-01d0-4cef-8eaf-ac123ca9c53d.png" alt="example" width="500"/>

**Comment by Laurynas-M** [comment]
Hello @iarenaza , @KepaUrzelai ,

I hope you are doing great!

I have tested the fix using the newest version (release 1.1.2) of multilang2, but this issue is still occurring with Canadian French language.
Could you check, if this can be fixed?

Thank you in advance.

**Comment by Laurynas-M** [comment]
Dear @iarenaza , @KepaUrzelai ,

I retested moodle-filter_multilang2 with committed fix https://github.com/KepaUrzelai/moodle-filter_multilang2/commit/0174b635d63e69a8d11b6dc50f453b0aff34d14b. 

It fixed the Canadian French (fr_ca) child's language issue reported in this ticket.

But a new issue occurred, which I reported in the ticket: https://github.com/iarenaza/moodle-filter_multilang2/issues/28.

Could you confirm this issue https://github.com/iarenaza/moodle-filter_multilang2/issues/28 with committed fix https://github.com/KepaUrzelai/moodle-filter_multilang2/commit/0174b635d63e69a8d11b6dc50f453b0aff34d14b?

If confirmed, could you fix it?


Thank you in advance.

**Comment by iarenaza** [comment]
Hi @Laurynas-M ,

I just published to Github (but not to the Moodle plugins site yet) an alpha version of the plugin that includes the configuration setting (and associated behaviour) discussed in issue #42.The alpha version is available as a release here in Github, at https://github.com/iarenaza/moodle-filter_multilang2/releases/tag/2.0.5-alpha-1

You should configure the plugin with the "Never use parent languages option" to get the behaviour that you want. If you could test that it works the way you expect, I would be very grateful!

Once you and the participants in issue #42 confirm that the alpha version works as expected, we can publish a new official release with the changes.

Saludos,

Iñaki

**Comment by iarenaza** [comment]
The changes created in issue #42, that also allow to solve this issue (by choosing the "Never use parent languages" option for the new setting), have been published in version 2.0.5 of the plugin.

So I'm closing this issue as fixed.
