### ISSUE TITLE
Tooltip texts are not translated.

### ISSUE THREAD

**Issue by JSGitHubbing** [iarenaza/moodle-filter_multilang2#31]
Hi,

I'm having some issues working with moodle filters and somehow I've ended up tryign this filter.

In the version v1.1.2 when the user hovers an element, if the tooltip is the name of a course the text is not translated and is shown all the code instead.

![imagen](https://user-images.githubusercontent.com/60095712/171371102-e95ca56e-74bd-4801-80e9-1e1048d7e809.png)

I'm not sure if this is an expected behaviour due to moodle multilang is having the same issue.

Is there any possibility to solve this?

Thank you all for your work in advance.

**Comment by izendegi** [comment]
Hi @JSGitHubbing 

It seems like the theme you are using doesn't support filters correctly on that hover, so it should be fixed on the theme.

It should be something quite easy to fix, it should be similar to this changes:
https://github.com/izendegi/moodle-theme_fordson/commit/dd32cf585e3bd865a759fdc79ca2289d2c5119b3

**Comment by JSGitHubbing** [comment]
Hi @izendegi 

Indeed it was due to the the I was using didn't supported the translation. 

Thanks a lot for your support and for the work you do. ♥
