### ISSUE TITLE
Multilanguage tabs shown in Search query results

### ISSUE THREAD

**Issue by briveradejesus** [iarenaza/moodle-filter_multilang2#38]
Hi! We are using the following multilanguage plugins with the Theme-Lambda 1.98.41 (2023012940) in Moodle 4.1.1+ (Build 20230203):
Multi-language content - filter_multilang
Multi-Language Content (v2) - filter_multilang2
Multi-Language Content (v2) - atto_multilang2

When we do a site search, the results present the multilanguage tags as shown in the screenshot below

<img width="678" alt="2023-07-12 11_14_34-Global search" src="https://github.com/iarenaza/moodle-filter_multilang2/assets/139369275/7767e4d9-cce6-4f5f-8ea7-08159c5202c3">

Any recommendations on how to solve this issue?

Regards!

**Comment by lucaboesch** [comment]
That's https://tracker.moodle.org/browse/MDL-67847 "Global search results don't honour multilang filter", @briveradejesus and thus isn't a filter/multilang2 bug.
This Issue can be closed.
Please comment and vote on the Moodle tracker Issue.

**Comment by iarenaza** [comment]
Closing the issue, as it's not a but in the filter itself.
