### ISSUE TITLE
Improve checks for parent languages

### ISSUE THREAD

**Issue by mudrd8mz** [iarenaza/moodle-filter_multilang2#4]
Instead of manually handling the parent language in the `replace_callback()` method, it would be better to make use of `string_manager::get_language_dependencies()`. It returns the whole chain of parent languages without the need to switch the current language.

**Comment by iarenaza** [comment]
Hi David,
as far as I can see, there isn't a string_manager class, and the only place where I can find the get_language_dependencies() method is in lib/classes/string_manager_standard.php (class core_string_manger_standard). But then, that method is not static. So I would need to instantiate a core_string_manager_standard (via get_string_manager() and then call the method you propose.

Is that what you had in mind? (looking at get_string_manager(), it seems a bit heavyweight just to be able to get the chain of parent language, but if you say that's a better way to deal with it, I'm fine with that.

**Comment by mudrd8mz** [comment]
Yes, that is what I mean - something like `get_string_manager()->get_language_dependencies($lang)`

> it seems a bit heavyweight

No worries. If you look at how `get_string()` is implemented, you will see that it internally uses the string manager instance too. There is singleton pattern used so the instance of the string manager already exists in the memory and it will be used for you. It does not create a new one.
