### ISSUE TITLE
Feedback block showing {mlang} tags instead of showing the right language

### ISSUE THREAD

**Issue by sH0k3n122** [iarenaza/moodle-filter_multilang2#41]
Hi,
I have a feedback activity on my main page, which is the parent to feedback blocks in all courses (simply to gather the opinions in one place). The {mlang} tags perfectly in the feedback activity, but it mixes up the blocks, shown under:,

Feedback activity: https://ibb.co/album/F6PP4f
Feedback block: https://ibb.co/qpKwS4w

I hope it counts as a bug and it'll get fixed :)

**Comment by lucaboesch** [comment]
Seems like a feedback block bug to me, not a filter_multilang2 bug.

**Comment by iarenaza** [comment]
I totally agree with @lucaboesch on this one: this definitely looks like a bug in the feedback module.

**Comment by iarenaza** [comment]
Hummm, now that I look at the images again (a lot of context is missing in them), maybe you just need to change the multilang v2 filter settings to apply the filter not just to the "Content" but to "Content and headings". Could that be it @sH0k3n122 ?

**Comment by sH0k3n122** [comment]
> Hummm, now that I look at the images again (a lot of context is missing in them), maybe you just need to change the multilang v2 filter settings to apply the filter not just to the "Content" but to "Content and headings". Could that be it @sH0k3n122 ?

Unfortunately, that's not the case. I changed the filter settings to apply the filter to "Content and headings" right after the installation.

**Comment by iarenaza** [comment]
In that case, it's clearly a bug in the feedback block. If the activity itself shows the correct language string (as opposed to the raw definition with the {mlang xx}...{mlang} tags) then the filter is working as expected. Most probably, the feedback block code is not using `format_string()` or `format_text()` to filter the strings before outputing them.

**Comment by izendegi** [comment]
Hi @sH0k3n122 

To fix this issue you should open an issue at tracker.moodle.org, but you can try fixing it yourself by adding what @iarenaza said here:

https://github.com/moodle/moodle/blob/d76e211be6ae65fe3982ad97f3fe5c879a7b2daa/blocks/feedback/block_feedback.php#L67

Something like this should work:

                $this->content->items[] = '<a href="'.$url->out().'">'.$icon.format_string($feedback->name).'</a>';
