### ISSUE TITLE
Not working with custom developed block 

### ISSUE THREAD

**Issue by Sakib3s** [iarenaza/moodle-filter_multilang2#43]
Hi,

I'm trying to use this plugin lan based content hide/show with my custom block, I have tried this code but not working:

  _{mlang XX}content in language XX{mlang}
  {mlang YY}content in language YY{mlang}
  {mlang other}content for other languages{mlang}_

It is possible to make my custom block input field support {mlang}?

Best

**Comment by izendegi** [comment]
Hi @Sakib3s ,

To make your block compatible with Moodle filters (not only with this plugin but [with all the core filters too](https://docs.moodle.org/403/en/Filters)), you have to give format to those texts on your block before showing them, usually using format_string or format_text functions:

[https://moodledev.io/docs/apis/subsystems/output#string-formatting-functions](https://moodledev.io/docs/apis/subsystems/output#string-formatting-functions)

**Comment by Sakib3s** [comment]
Thanks!

After returning data with format_text() function it's working.


Best
