### ISSUE TITLE
Issue when using H5P and the multilang2 plugin

### ISSUE THREAD

**Issue by Amberlaminin** [iarenaza/moodle-filter_multilang2#48]
Hi - I also want to thank you for the great plugin! I just had and issue when using it with H5P. It does not work when using H5P, and displays all the mlang tags. Is it possible to help? I am using Moodle4.4 
![multilangv2](https://github.com/iarenaza/moodle-filter_multilang2/assets/172260266/5add4c50-95c4-4d4b-b899-cbb41e57350e)

Thx
L

**Comment by iarenaza** [comment]
Hi @Amberlaminin 

unless things have changed in Moodle core sinde 3.8, Moodle filters are not applied to H5P content (see #16 )

So I'm afraid there is nothing we can do on our side to fix this.

**Comment by Amberlaminin** [comment]
Good day all,

 

Thanks for the reply. 

I got your multilangv2 plugin to work with the H5P content in Moodle – by using the <embed> functionality in a normal page. This can even keep track of grades if used with the H5P button, but I still could not figure out how to use it as the H5P activity.

 

I am still So satisfied with your plugin – this is a small price to pay.

 

Thanks!

 

Amberlaminin
