### ISSUE TITLE
Moodle 4.5 Compatibility Issue

### ISSUE THREAD

**Issue by michael-milette** [iarenaza/moodle-filter_multilang2#49]
Hi @iarenaza ,

Multilang2 is going to need some work in order to be made compatible with Moodle 4.5+. There are changes to the API for **filter** type plugins.

Feel free to take a look at how I worked it out for [FilterCodes](https://github.com/michael-milette/moodle-filter_filtercodes). Hope it helps.

On a side note, there is one line of difference between the pre-4.5 version (**master** branch) and the 4.5+ version (**MOODLE_405_STABLE** branch) of FilterCodes which is preventing me from continuing with a unified version that is compatible with all versions of Moodle. I am very interested to see if you can figure out a way to do it.

Best regards,

Michael Milette

**Comment by rezeau** [comment]
Same issue on my localhost testing moodle 4.5. In DEBUG I am getting this error:
PHP Notice:  Inclusion of filters from 'filter/multilang2/filter.php' using the 'filter_multilang2' class naming has been deprecated. Please rename your class to \filter_multilang2\text_filter and move it to 'filter/multilang2/classes/text_filter.php'. See MDL-82427 for more information.

**Comment by iarenaza** [comment]
Thanks for the heads up. I'll have a look at the changes proposed at https://tracker.moodle.org/browse/MDL-82427 MDL-81125 and see what I can do.

Notice in any case that we don't mention 4.5 compatibility in the Moodle plugins database (yet :smile: ).

**Comment by michael-milette** [comment]
I know it wasn't listed. Really, this was just a heads up. I noticed Justin Hunt has updated his Video Easy Filter plugin which he seems to have a working unified version. I am going to check out how he managed to do it.

**Comment by iarenaza** [comment]
This commit seem to be where the magic happens: https://github.com/justinhunt/moodle-filter_videoeasy/commit/0b7e0ec6af79a8bd01b442c77b9b4fdb15d59530

This other one might be required for PHP 8.2 support (I think we don´t need this one in multilang2, as we use a different approach): https://github.com/justinhunt/moodle-filter_videoeasy/commit/9f349c091393301390a4048d131360e6afabb0e5

**Comment by michael-milette** [comment]
Thanks for the tip.

Yup! I found Justin's Video Easy filter and applied similar changes to FilterCodes. It worked like a charm. I am back to one unified version. 😎👍

I didn't need to make the same changes for PHP 8.2 either.

Best regards,

Michael

**Comment by lucaboesch** [comment]
In

`
if (class_exists('\core_filters\text_filter')) {
    class_alias('\core_filters\text_filter', 'base_text_filter');
} else {
    class_alias('\moodle_text_filter', 'base_text_filter');
}

class text_filter extends \base_text_filter {
`

"base_text_filter" is too generic, though.
If, in parallel, a filter plugin is installed which uses the same trick, a warning would pop up saying base_text_filter is already defined.
IMHO filter_multilang2_base_text_filter would be better.

**Comment by michael-milette** [comment]
That's what I did too for FilterCodes. I prefixed it with "filter_filtercodes_".

**Comment by justinhunt** [comment]
I also did that in a later commit, because it bombed straight away when I used the same trick for my other filters. Glad it was useful

**Comment by iarenaza** [comment]
Thanks to everybody that contributed to make the plugin compatible with Moodle 4.5, while at the same time making it work with previous 4.x version!

I'm closing the issue now.

**Comment by michael-milette** [comment]
Thank you @iarenaza
