### ISSUE TITLE
Issue with 2.0.3 and Moodle 4.1

### ISSUE THREAD

**Issue by izendegi** [iarenaza/moodle-filter_multilang2#54]
Kaixo, Iñaki

I've seen [in the forums](https://moodle.org/mod/forum/discuss.php?d=462961) that people are reporting errors with the last version of the plugin (2.0.3) and Moodle 4.1

The previous one (2.0.2) was marked compatible only with 4.2 and newer versions, so I guess the problem is with Moodle 4.1 and as a temporary measure I've marked [the 2.0.3 version only compatible only with 4.2 and newer versions in the plugins database](https://moodle.org/plugins/filter_multilang2/2.0.3/33437)

**Comment by iarenaza** [comment]
@izendegi  Thanks for the heads up!

The CI test matrix checks with MOODLE_401_STABLE version, which is only the latest 4.1.x version. So maybe earlier 4.1 versions are missing some compatibility machinery? I'll test with all of them, and see what can be done.

**Comment by iarenaza** [comment]
Hummm, curiously enough it seems to work without trouble on a freshly installed Moodle 4.1.13 (Build: 20241007) I just created.

It's also quite telling that the error both reporters mention is "Class 'filter_multilang2\text_filter' not found". Which is exactly the same issue reported as #53 . Which seems to be not a coding error, but a cache invalidation issue? As purging the caches seems to fix the issue completely. Maybe purging them all is not needed (as that could introduce a performance hit until they are repopulated again), but I don't know which is the one that should be purged.

I'll mention the "fix" in those two threads.

**Comment by iarenaza** [comment]
I  published version 2.0.4 of the plugin in the Moodle Plugins directory, with the the fix from PR #55.

I'll wait for a few days until people having issues with 2.0.3 can confirm that 2.0.4 fixes those problems, before closing this issue.

**Comment by izendegi** [comment]
Closing this as fixed

https://moodle.org/mod/forum/discuss.php?d=462953#p1859070
