### ISSUE TITLE
Review Basque translation for latest language changes

### ISSUE THREAD

**Issue by iarenaza** [iarenaza/moodle-filter_multilang2#56]
Hi @KepaUrzelai , @izendegi,

could you have a look at the Basque translation I did in commit 381cb034cef3aa ?

I'm not completely sure that translation is as good as it could be :smile: 

Thanks a lot in advance!

**Comment by izendegi** [comment]
Kaixo @iarenaza!

I already had those strings translated to Basque in AMOS, I'll take a look to your translation and try to pick the best of both ;-)

**Comment by izendegi** [comment]
Hi again, @iarenaza 

I've already done it at #57
