### ISSUE TITLE
Not working on "Available Courses" block in the home page.

### ISSUE THREAD

**Issue by sirpepo** [iarenaza/moodle-filter_multilang2#6]
In the homepage as guest, the "Available Courses" block is printing the markup for languages and not only the content for the current language.

**Comment by iarenaza** [comment]
Hi,

could you provide a screenshot showing the problem? I would need to identify what content the markup for languages is related to (title of the course, description, shortname, etc.) and how/where it is shown.

Thanks in advance.

**Comment by iarenaza** [comment]
Closing this, as I've been unable to reproduce the problem (and no feedback has been received).
