### ISSUE TITLE
Add pluginname string to language pack

### ISSUE THREAD

**Issue by abias** [iarenaza/moodle-filter_multilang2#7]
Hi,

I noticed that the plugin only defines
`$string['filtername']`
in the language pack.

At least when Moodle looks for available updates of the plugin and sends an email to the administrator, it looks for
`$string['pluginname']`
in the language pack.

At the moment, the result in the notification mail looks like this (in german):

> Aktualisierung für Plugins verfügbar!
> [[pluginname]] (filter_multilang2) Eine neue Version 2016080700 ist verfügbar!

Would you mind adding the pluginname string to the language pack of the plugin?

Thanks,
Alex

**Comment by iarenaza** [comment]
Hi Alex,

I'have just added the pluginname language strings to all supported versions of the plugin and pushed a new version to GitHub. I'll push and updated version to Moodle plugins database in a few minutes.

Thanks for the heads up
